name: Publish Release

on:
  release:
    # 'published' fires for both stable releases and prereleases
    types: [published]

permissions: {}

jobs:
  build-and-test-windows:
    name: publish/build-and-test-windows
    permissions:
      contents: read # Required to checkout repository code
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: "false"
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x
      - name: Set up Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: stable
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Run tests
        run: npm test
  publish:
    name: publish/publish
    needs: build-and-test-windows
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read # Required to checkout repository code
      security-events: write # Required to write security events for SAST results
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: "false"
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x
      - name: Update npm
        run: npm install -g npm@11.7.0
      - name: Set up Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: stable
      - name: Install dependencies
        run: npm ci
      - name: Run prettier
        run: npm run prettier:check
      - name: Run lint
        run: npm run lint
      - name: Build package
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Run tests using Hardhat Node
        run: npm run test:node
      - name: Run tests using Anvil
        run: npm run test:anvil
      - name: Run zizmor ðŸŒˆ
        uses: zizmorcore/zizmor-action@e673c3917a1aef3c65c972347ed84ccd013ecda4 # v0.2.0
        with:
          persona: pedantic
          version: 1.14.2
      - name: Set NPM version tag to latest
        if: ${{ github.event_name == 'release' && !github.event.release.prerelease }}
        run: |
          echo "NPM_TAG=latest" >> "${GITHUB_ENV}"
      - name: Set NPM version tag to prerelease
        if: ${{ github.event_name == 'release' && github.event.release.prerelease }}
        run: |
          echo "NPM_TAG=prerelease" >> "${GITHUB_ENV}"
      - name: Publish mock-utils release to npm
        uses: JS-DevTools/npm-publish@7f8fe47b3bea1be0c3aec2b717c5ec1f3e03410b # v4.1.1
        with:
          package: packages/mock-utils/src
          provenance: true
          access: public
          tag: ${{ env.NPM_TAG }}
      - name: Publish hardhat-plugin release to npm
        uses: JS-DevTools/npm-publish@7f8fe47b3bea1be0c3aec2b717c5ec1f3e03410b # v4.1.1
        with:
          package: packages/hardhat-plugin
          provenance: true
          access: public
          tag: ${{ env.NPM_TAG }}
